### ISSUE TITLE
Allow using a PlantUML configuration file

### ISSUE THREAD

**Issue by jmezach** [mikitex70/plantuml-markdown#88]
It would be nice if this extension would allow me to configure the location of a PlantUML config file. This would allow us to configure some global settings that apply to all the diagrams generated through PlantUML. Such a config file can be passed to the `plantuml` binary through the `-config` switch (see the [documentation](https://plantuml.com/command-line#85c7e8fde73fc8d8)).

I'm thinking this could be a configurable option for the plantuml-markdown extension similar to how other options are configured. Obviously this would only work when using the `local` rendering mode as I don't think we can pass such a file to a PlantUML server, but that is fine at least for my purposes ;).

Again I'd be more than happy to submit a PR for this.

**Comment by mikitex70** [comment]
Hi @jmezach, I have released version '3.9.0' which has the 'config' plugin configuration option.
The configured file is passed to plantuml with the `-config` command-line option.
 The file is considered to be related to the `base_dir` configuration option so that the file can also be used with plantuml servers.

**Comment by mikitex70** [comment]
If you use a local plantuml and you set the `base_dir` option, you MUST also set the `plantuml_cmd` option and pass the path with the `-Dplantuml.include.path` java option.
There is no other way to inform plantuml of the directory were to search for includes.
